import { createContext, useState } from "react";

export const NigeriaContext = createContext();

export const NigeriaProvider = ({ children }) => {
  const [states, setStates] = useState([
    {
      name: "Abia",
      description: "Abia State, created on August 27, 1991, was carved out of the old Imo State. The state is located in southeastern Nigeria and is predominantly occupied by the Igbo ethnic group. Historically, Abia has been a major center for trade, agriculture, and industry, with Aba serving as a commercial hub since the colonial era. The Aba Women’s Riot of 1929, a significant anti-colonial protest led by women, remains a key historical event. Today, Abia is known for its entrepreneurial spirit and industrial activities.",
      population: "Abia State has an estimated population of around 3.7 million people. The population is densely concentrated in cities like Aba and Umuahia, the state capital. Aba, often called the Japan of Africa, is famous for its manufacturing and trade, attracting thousands of businesspeople. The population is predominantly Igbo, with a strong presence of artisans, traders, and farmers. Over the years, rapid urbanization has led to growth in infrastructure, education, and commerce, making Abia a key economic player in Nigeria.",
      safetydetails: "Abia State is relatively safe, especially in cities like Umuahia (the capital) and major towns. However, in some areas, issues like petty theft, traffic congestion, and occasional civil disturbances can occur. Travelers should: Stick to well-populated areas and avoid late-night movements in unfamiliar locations, Use trusted transportation services, such as ride-hailing apps or private cabs, Be cautious in markets like Ariaria due to pickpocketing, Stay updated on local news for any security advisories.",
      funfact1: "⭐ Aba Women’s Riot (1929) – One of the first anti-colonial protests in Nigeria was led by women in Aba.",
      funfact2: "⭐ Ariaria International Market – One of the largest markets in West Africa, famous for locally made goods.",
      funfact3: "Home of Aba-made Products – Shoes, clothes, and leatherworks from Aba are exported internationally.",
      culturetitle: "Abia’s culture is deeply rooted in Igbo traditions, with strong values of entrepreneurship, community, and hospitality.",
      culture1: " New Yam Festival (Iri Ji) – A major annual event celebrating harvest, marked with dances, feasts, and masquerades.",
      culture2: "Igbo Language & Proverbs – The Igbo language is widely spoken, with proverbs often used in conversation.",
      culture3: "Handcrafts & Arts – Aba artisans are known for producing quality textiles, footwear, and leatherworks."
    },
    {
      name: "Abuja",
      description: "Abuja, Nigeria's capital, officially became the country’s seat of power in 1991, replacing Lagos. Designed as a planned city, Abuja was chosen for its central location and neutrality among ethnic groups. It is home to Nigeria’s government institutions, foreign embassies, and many multinational corporations. The city is known for its well-structured roads, modern architecture, and iconic landmarks like Aso Rock and the National Mosque.",
      population: "Abuja has an estimated population of over 3.6 million people and continues to grow due to migration. The city attracts professionals, expatriates, and government officials, making it one of Nigeria’s most diverse regions. With a mix of indigenous Gwari people and settlers from all parts of Nigeria, Abuja serves as a melting pot of cultures.",
      safetydetails: "Abuja is one of Nigeria’s safest cities due to strong security presence, especially in government areas. However, petty crimes such as phone snatching and scams occur in busy locations. Travelers should avoid isolated areas at night and stay cautious around markets and public parks.",
      funfact1: "⭐ Abuja is one of the fastest-growing cities in Africa.",
      funfact2: "⭐ The city was designed by an international team of architects in the 1980s.",
      funfact3: "⭐ Aso Rock, a massive rock formation, is one of the city's most famous landmarks.",
      culturetitle: "Abuja's culture is a blend of Nigerian traditions, influenced by its diverse population.",
      culture1: "FCT Carnival – An annual festival showcasing Nigeria’s rich cultural diversity.",
      culture2: "Gwari Pottery – Traditional pottery-making is a historic craft of Abuja’s indigenous people.",
      culture3: "International Cuisine – Due to its diverse population, Abuja has a variety of local and international restaurants."
    },
    {
      name: "Kano",
      description: "Kano, founded over a thousand years ago, is one of Nigeria’s oldest cities and a major hub for trade and Islamic culture. As the commercial center of northern Nigeria, Kano has a rich history of trans-Saharan trade, textile production, and traditional crafts. The city is famous for its ancient walls, historical markets, and strong Islamic influence.",
      population: "With a population of over 15 million, Kano is the second-largest city in Nigeria. The majority of its people are Hausa-Fulani, and the city remains a stronghold of northern traditions, Islam, and trade activities. Kano’s large population drives its vibrant markets, industries, and educational institutions.",
      safetydetails: "Kano is generally safe, but visitors should be mindful of cultural sensitivities. It is advisable to dress modestly, avoid discussing politics or religion openly, and stay aware of local security updates. Markets can be crowded, making pickpocketing a concern.",
      funfact1: "⭐ Kano is home to Kurmi Market, one of the oldest markets in West Africa.",
      funfact2: "⭐ Kano’s ancient walls date back over 1,000 years.",
      funfact3: "⭐ The city has one of Nigeria’s largest textile and leather industries.",
      culturetitle: "Kano’s culture is deeply rooted in Islamic traditions and Hausa heritage.",
      culture1: "Durbar Festival – A grand celebration featuring horse parades and traditional displays.",
      culture2: "Hausa Cuisine – Specialties like suya, kilishi, and tuwo shinkafa are widely enjoyed.",
      culture3: "Traditional Dyeing Pits – Kano’s Kofar Mata dye pits are among the oldest in Africa."
    },
    {
      name: "Rivers",
      description: "Rivers State, created in 1967, is located in the Niger Delta region and is known for its oil production and rich cultural heritage. The capital, Port Harcourt, serves as Nigeria’s oil hub, attracting both local and international companies. The state is also known for its vibrant riverine communities and beautiful landscapes.",
      population: "Rivers State has a population of over 7 million people, comprising a mix of ethnic groups, including the Ikwerre, Ogoni, and Ijaw. The oil industry has led to rapid urbanization, with many people migrating to Port Harcourt for job opportunities.",
      safetydetails: "While Rivers State, especially Port Harcourt, is relatively safe, some areas experience challenges like traffic congestion, protests, and occasional security concerns. Visitors should stay updated on local news, avoid isolated areas, and use reliable transportation services.",
      funfact1: "⭐ Rivers State is home to Bonny Island, a key location for Nigeria’s oil and gas industry.",
      funfact2: "⭐ The state has one of the highest GDPs in Nigeria due to oil revenue.",
      funfact3: "⭐ It hosts the famous Garden City Literary Festival.",
      culturetitle: "Rivers State has a rich cultural mix of traditions, music, and festivals.",
      culture1: "Owu Festival – A major event among the Ijaw people, featuring boat regattas and cultural displays.",
      culture2: "Seafood Cuisine – Rivers is famous for its fresh seafood, including periwinkles and catfish pepper soup.",
      culture3: "Nollywood Influence – Port Harcourt has contributed to Nigeria’s film and entertainment industry."
    },
    {
        name: "Adamawa",
        description: "Adamawa State, located in northeastern Nigeria, was created in 1991 from the former Gongola State. It shares a border with Cameroon and is known for its rich cultural diversity, scenic landscapes, and agricultural activities. The state is home to several ethnic groups, including the Fulani, Hausa, and Bachama.",
        population: "Adamawa has an estimated population of around 4.2 million people. The majority of the population engages in farming and cattle rearing, with Yola, the state capital, serving as a key administrative and economic center.",
        safetydetails: "Adamawa has faced security challenges in recent years, particularly in rural areas. However, Yola and other major towns remain relatively safe. Travelers should: Avoid remote areas prone to security risks, Stay in secure accommodations, Follow local security advisories and travel warnings.",
        funfact1: "⭐ Adamawa has beautiful highlands and waterfalls, making it a great destination for nature lovers.",
        funfact2: "⭐ The state is home to Modibbo Adama University, a leading educational institution.",
        funfact3: "Adamawa’s cattle trade is one of the biggest in Nigeria, attracting buyers from across the country.",
        culturetitle: "Adamawa’s culture is a mix of Fulani, Hausa, and other indigenous traditions.",
        culture1: "Fulani Festivals – Celebrations such as the Durbar festival showcase horse riding and traditional displays.",
        culture2: "Traditional Music – The use of drums, flutes, and folk singing is common in local celebrations.",
        culture3: "Cuisine – Popular dishes include Kilishi (dried meat) and Fura da Nono (millet and milk drink)."
      },
      {
        name: "Akwa-Ibom",
        description: "Akwa Ibom, located in southern Nigeria, was created in 1987 from Cross River State. It is known for its rich oil and gas resources, beautiful beaches, and cultural heritage. The state capital, Uyo, is one of the fastest-growing cities in Nigeria.",
        population: "Akwa Ibom has a population of approximately 5.5 million people. The Ibibio, Annang, and Oron ethnic groups dominate the state. Urbanization and industrialization are on the rise, contributing to rapid economic growth.",
        safetydetails: "Akwa Ibom is generally safe, with Uyo being one of the most peaceful state capitals. However, travelers should: Be cautious in rural areas, Use only trusted transport services, Avoid walking alone at night.",
        funfact1: "⭐ Home to Ibom Air, Nigeria’s first state-owned airline.",
        funfact2: "⭐ Features the longest bridge in southern Nigeria, the Ikot Abasi Bridge.",
        funfact3: "Akwa Ibom has some of the best seafood dishes in Nigeria.",
        culturetitle: "Akwa Ibom’s culture is deeply tied to its Ibibio roots.",
        culture1: "Ekpe Masquerade – A traditional performance seen during festivals.",
        culture2: "Traditional Cuisine – Afang soup and Editan soup are popular dishes.",
        culture3: "Music & Dance – Traditional dances such as Ekombi are widely performed."
      },
      {
        name: "Bauchi",
        description: "Bauchi State, created in 1976 from the former North-Eastern State, is located in northeastern Nigeria. It is known for its rich cultural heritage, historical sites, and diverse ethnic groups. The state is home to the Yankari National Park, a popular tourist attraction featuring wildlife and natural warm springs.",
        population: "Bauchi State has an estimated population of around 6.5 million people. The majority of the inhabitants are Hausa, Fulani, and other minority ethnic groups. Agriculture and trade are the main economic activities, with Bauchi city serving as the commercial and administrative center.",
        safetydetails: "Bauchi is generally safe, especially within major towns and cities. However, rural areas may experience security challenges. Travelers should: Avoid isolated areas, Use verified transportation services, Stay informed about local security updates.",
        funfact1: "⭐ Yankari National Park – Home to elephants, lions, and the famous Wikki Warm Springs.",
        funfact2: "⭐ Bauchi is named after a hunter, a tribute to the state's early hunting tradition.",
        funfact3: "Bauchi State has a rich history of Islamic scholarship and traditional leadership.",
        culturetitle: "Bauchi’s culture is influenced by the Hausa and Fulani traditions.",
        culture1: "Durbar Festival – A colorful horse-riding event during celebrations.",
        culture2: "Traditional Weaving – The state is known for handwoven fabrics and crafts.",
        culture3: "Cuisine – Bauchi is famous for dishes like Masa (rice cake) and Tuwo Shinkafa."
      },
      {
        name: "Borno",
        description: "Borno State, created in 1976, is located in northeastern Nigeria. It is the largest state by landmass and historically significant as the center of the Kanem-Bornu Empire. The state capital, Maiduguri, is a major commercial and cultural hub in the region.",
        population: "Borno has an estimated population of around 5.8 million people. The Kanuri people form the dominant ethnic group, with Shuwa Arabs, Hausa, and other minorities also present. The economy is driven by agriculture, livestock rearing, and trade.",
        safetydetails: "Borno has experienced security challenges in recent years, especially in rural areas. However, Maiduguri is relatively stable. Travelers should: Follow official travel advisories, Avoid rural and conflict-prone areas, Use trusted local guides if necessary.",
        funfact1: "⭐ Borno was the heart of the Kanem-Bornu Empire, one of Africa’s oldest kingdoms.",
        funfact2: "⭐ The Shehu of Borno is one of Nigeria’s most respected traditional rulers.",
        funfact3: "Maiduguri is famous for its delicious Kilishi (spiced dried meat).",
        culturetitle: "Borno has a deep-rooted Kanuri and Islamic cultural influence.",
        culture1: "Shehu’s Palace – A historic site symbolizing the Kanuri dynasty.",
        culture2: "Traditional Music – Unique drums and instruments used in celebrations.",
        culture3: "Local Crafts – Intricate embroidery and leatherworks are popular."
      },
      {
        name: "Cross River",
        description: "Cross River State, created in 1976, is located in southern Nigeria. It is known for its lush rainforest, ecotourism, and vibrant culture. The state capital, Calabar, is a major tourist destination famous for its annual carnival and historical sites.",
        population: "Cross River has an estimated population of around 4 million people. The Efik, Ejagham, and Bekwarra are the dominant ethnic groups. Fishing, agriculture, and tourism drive the state’s economy.",
        safetydetails: "Cross River is one of the safest states in Nigeria, particularly in Calabar. Travelers should: Be cautious in rural areas, Use registered transport services, Stay updated on local events.",
        funfact1: "⭐ Calabar Carnival is Africa’s biggest street party, attracting tourists worldwide.",
        funfact2: "⭐ Cross River National Park is home to rare gorillas and diverse wildlife.",
        funfact3: "Calabar is known for its historic slave trade museums and colonial architecture.",
        culturetitle: "Cross River’s culture is colorful and deeply rooted in Efik traditions.",
        culture1: "Ekpe Masquerade – A significant cultural and spiritual event.",
        culture2: "Delicious Cuisine – Afang Soup and Edikang Ikong are popular dishes.",
        culture3: "Traditional Dance – The Efik people perform elaborate dances at festivals."
      },
      {
        name: "Ebonyi",
        description: "Ebonyi State, created in 1996, is located in southeastern Nigeria. It was formed from parts of Enugu and Abia states. The state is known for its rich agricultural base, with rice, yam, and cassava being major crops. Abakaliki, the capital, is famous for its rice mills and salt lakes. Ebonyi is home to various tourist attractions, including the Abakaliki Green Lake and the Unwana Beach. The people are predominantly Igbo, with a deep-rooted cultural heritage and strong entrepreneurial spirit.",
        population: "Ebonyi State has an estimated population of around 3 million people. The population is mostly rural, with farming as the predominant occupation. Urban centers like Abakaliki are experiencing growth due to increased investment in infrastructure, commerce, and education.",
        safetydetails: "Ebonyi is relatively safe, but travelers should be cautious in remote areas. Stick to major cities and use reliable transportation services.",
        funfact1: "⭐ Abakaliki Rice – One of Nigeria’s most renowned rice-producing areas.",
        funfact2: "⭐ Ebonyi has large deposits of salt, leading to its nickname ‘Salt of the Nation’.",
        funfact3: "The state is known for its beautiful tourist attractions, such as the Unwana Beach and Okposi Salt Lake.",
        culturetitle: "Ebonyi’s culture is rich in Igbo traditions and vibrant festivals.",
        culture1: "New Yam Festival – Celebrated yearly to mark the harvest season.",
        culture2: "Masquerade Festivals – Colorful displays of cultural heritage and traditional beliefs.",
        culture3: "Igbo Traditional Wrestling – A significant part of social life and entertainment."
      },
      {
        name: "Ekiti",
        description: "Ekiti State, created in 1996, is located in southwestern Nigeria. The state is known for its hilly terrain, which gives it the name ‘Land of Honour and Integrity.’ Agriculture is the backbone of Ekiti’s economy, with cocoa, yam, and rice being major crops. Ado-Ekiti, the capital, is a growing hub for education and commerce. Ekiti is rich in cultural heritage, hosting traditional festivals and showcasing Yoruba customs, making it one of the most historically significant states in Nigeria.",
        population: "Ekiti State has an estimated population of around 3.3 million people. The majority are Yoruba, with a high literacy rate due to the presence of many educational institutions. Farming remains a primary occupation.",
        safetydetails: "Ekiti is generally peaceful, but visitors should remain cautious and follow local guidelines when traveling in remote areas.",
        funfact1: "⭐ Known as the ‘Fountain of Knowledge’ due to its emphasis on education.",
        funfact2: "⭐ Home to Ikogosi Warm Springs, a rare natural phenomenon where warm and cold springs meet.",
        funfact3: "The state has one of the highest literacy rates in Nigeria.",
        culturetitle: "Ekiti’s culture is deeply rooted in Yoruba traditions.",
        culture1: "Ekiti Parapo War Festival – Celebrating historical alliances and bravery.",
        culture2: "Ewi Festival – A festival honoring traditional rulers and unity.",
        culture3: "Traditional Yoruba Pottery – A well-known craft in the state."
      },
      {
        name: "Enugu",
        description: "Enugu State, created in 1991, is located in southeastern Nigeria. It was carved out of the old Anambra State and is known for its coal mining heritage, which earned it the nickname ‘Coal City State.’ The capital, Enugu, is a major cultural and commercial center in the region. The state has a strong literary and artistic tradition, producing notable Nigerian writers and musicians. Enugu also boasts natural attractions like the Awhum Waterfalls and the Ngwo Pine Forest.",
        population: "Enugu has an estimated population of around 4.4 million people. The state is predominantly Igbo, with commerce, agriculture, and education playing key roles in its economy.",
        safetydetails: "Enugu is one of the safest states in Nigeria. However, travelers should take standard precautions when exploring remote areas.",
        funfact1: "⭐ The first coal mine in Nigeria was established in Enugu in 1909.",
        funfact2: "⭐ Enugu is home to Nollywood, Nigeria’s booming film industry.",
        funfact3: "The state has many stunning waterfalls and nature reserves.",
        culturetitle: "Enugu has a strong Igbo cultural identity.",
        culture1: "Mmanwu Festival – A colorful masquerade festival celebrated by locals.",
        culture2: "Igbo Highlife Music – Popularized by musicians from Enugu.",
        culture3: "Traditional Attire – Igbo cultural dressing remains prominent."
      },
      {
        name: "Gombe",
        description: "Gombe State, located in northeastern Nigeria, was created in 1996 from Bauchi State. It is known as the 'Jewel in the Savannah' and has a mix of savannah and semi-arid climate. The state's economy is primarily driven by agriculture, with crops like maize, millet, and groundnuts being dominant.",
        population: "Gombe has an estimated population of about 3.2 million people, with major ethnic groups including the Fulani, Hausa, Tangale, and Tera. The capital, Gombe city, serves as a commercial and administrative hub.",
        safetydetails: "Gombe is relatively safe but has occasional security concerns, especially in rural areas. Travelers are advised to stay within city centers and use verified transport services.",
        funfact1: "⭐ Home to the famous Gombe Stream National Park, a conservation area for wildlife.",
        funfact2: "⭐ Known for its annual hunting festival, which showcases local hunting traditions.",
        funfact3: "⭐ One of the fastest-growing states in the northeast due to infrastructural development.",
        culturetitle: "Gombe has a rich cultural heritage, influenced by its diverse ethnic composition.",
        culture1: "Tangale Dance Festival – A cultural event that features traditional dances and music.",
        culture2: "Durbar Festival – A horse-riding festival showcasing the Fulani and Hausa heritage.",
        culture3: "Handwoven Fabrics – Locally made fabrics and crafts are a significant part of Gombe’s culture.",
      },
      {
        name: "Jigawa",
        description: "Jigawa State, created in 1991 from Kano State, is located in northwestern Nigeria. It is predominantly an agricultural state, producing crops like rice, sorghum, and millet. The state has a vast expanse of arid land, with seasonal rivers and wetlands.",
        population: "Jigawa has an estimated population of around 5.8 million people, with the Hausa and Fulani ethnic groups being predominant. Dutse, the state capital, is a fast-developing city with growing commercial activities.",
        safetydetails: "Jigawa is generally peaceful, but travelers should be cautious in border towns due to potential security risks.",
        funfact1: "⭐ Home to the Hadejia-Nguru Wetlands, an important biodiversity zone.",
        funfact2: "⭐ Known for its historical connection to the Trans-Saharan trade routes.",
        funfact3: "⭐ Jigawa produces some of the best rice in Nigeria.",
        culturetitle: "Jigawa has a rich Islamic and Hausa-Fulani cultural heritage.",
        culture1: "Argungu Fishing Festival – A popular festival featuring traditional fishing competitions.",
        culture2: "Hausa Architecture – The state boasts unique traditional architectural designs.",
        culture3: "Farming Festivals – Celebrations of harvest and communal farming activities.",
      },
      {
        name: "Katsina",
        description: "Katsina State, created in 1987, is located in northwestern Nigeria and shares a border with Niger Republic. The state has a strong historical significance, being a center of Islamic learning and Hausa civilization.",
        population: "Katsina has an estimated population of over 7.8 million people, with the Hausa and Fulani being the major ethnic groups. The capital, Katsina city, is a key economic and cultural center in northern Nigeria.",
        safetydetails: "Katsina has experienced some security challenges, particularly in rural areas. Travelers should remain vigilant and follow security advisories.",
        funfact1: "⭐ Home to the famous Gobarau Minaret, a centuries-old Islamic tower.",
        funfact2: "⭐ Katsina is known as the ‘Home of Hospitality.’",
        funfact3: "⭐ The first university in Northern Nigeria, Umaru Musa Yar’adua University, is located here.",
        culturetitle: "Katsina is deeply rooted in Islamic and Hausa traditions.",
        culture1: "Durbar Festival – A grand equestrian display held during Eid celebrations.",
        culture2: "Traditional Leatherworks – Katsina is famous for its high-quality leather products.",
        culture3: "Islamic Scholarship – The state has numerous Quranic and Islamic learning centers.",
      },
      {
        name: "Kogi",
        description: "Kogi State, created in 1991, is located in central Nigeria and is home to the confluence of the Niger and Benue rivers. The state is rich in natural resources and serves as a major transit route between northern and southern Nigeria. Lokoja, the state capital, was historically the first administrative capital of Nigeria during colonial rule. Kogi is home to several ethnic groups, including Igala, Ebira, and Okun, making it one of Nigeria’s most culturally diverse states.",
        population: "Kogi State has a population of approximately 4.5 million people, with a mix of rural and urban settlements. Lokoja, the capital, is a key trading hub.",
        safetydetails: "Kogi is generally safe, but travelers should be cautious in remote areas due to occasional security concerns. Urban centers like Lokoja are more secure, but petty crime can occur.",
        funfact1: "⭐ Lokoja was the first administrative capital of Nigeria.",
        funfact2: "⭐ The state is home to Mount Patti, where Lord Lugard named Nigeria.",
        funfact3: "⭐ The Confluence of Rivers Niger and Benue is a major geographical landmark in Kogi.",
        culturetitle: "Kogi’s culture is shaped by its multi-ethnic population.",
        culture1: "Ibegwu Festival – A significant Igala festival honoring ancestors.",
        culture2: "Ebira Masquerade Festival – A colorful and vibrant event with rich traditions.",
        culture3: "Traditional Weaving – Handwoven fabrics are a key cultural heritage."
      },
      {
        name: "Kwara",
        description: "Kwara State, established in 1967, is in western Nigeria and shares a border with Benin Republic. The state’s economy thrives on agriculture, trade, and education, with Ilorin, the state capital, serving as a major educational hub. Kwara is known for its cultural blend of Yoruba, Nupe, and Bariba ethnic groups. The state hosts several tourist attractions, including the Esie Museum, home to ancient stone carvings, and Owu Waterfalls, one of Nigeria’s tallest waterfalls.",
        population: "Kwara has a population of about 3.2 million people, with Ilorin being the most populous city.",
        safetydetails: "Kwara is relatively peaceful, but travelers should be mindful of local safety advisories in remote areas.",
        funfact1: "⭐ Kwara is home to Nigeria’s first museum, the Esie Museum.",
        funfact2: "⭐ Owu Waterfalls, the highest waterfall in West Africa, is in Kwara.",
        funfact3: "⭐ Ilorin has one of the oldest Islamic schools in Nigeria.",
        culturetitle: "Kwara's culture is a mix of Yoruba and northern influences.",
        culture1: "Durbar Festival – A colorful equestrian parade during Islamic celebrations.",
        culture2: "Ilorin Pottery – Traditional pottery making is a key heritage.",
        culture3: "Local Cuisine – Popular dishes include Amala and Ilorin’s signature soups."
      },
      {
        name: "Kebbi",
        description: "Kebbi State, created in 1991, is located in northwestern Nigeria and is known for its rich history and agricultural economy. The state is a leading producer of rice in Nigeria, contributing significantly to food security. Birnin Kebbi, the capital, is an important trade center with strong ties to neighboring Niger. Kebbi hosts the Argungu Fishing Festival, a famous cultural event that attracts visitors from across the country and beyond, celebrating fishing traditions and local heritage.",
        population: "Kebbi State has a population of about 4.4 million people, with agriculture being the main occupation.",
        safetydetails: "Kebbi is generally safe, but travelers should remain cautious in border areas.",
        funfact1: "⭐ Kebbi is Nigeria’s top rice-producing state.",
        funfact2: "⭐ The Argungu Fishing Festival is one of the oldest festivals in Nigeria.",
        funfact3: "⭐ The state shares a border with the Republic of Niger.",
        culturetitle: "Kebbi’s culture reflects its strong Hausa-Fulani traditions.",
        culture1: "Argungu Fishing Festival – A globally recognized cultural event.",
        culture2: "Hausa Architecture – The state has unique traditional buildings.",
        culture3: "Traditional Wrestling – A popular sport in Kebbi’s rural communities."
      },
      {
        name: "Nasarawa",
        description: "Nasarawa State, created in 1996, is located in central Nigeria and is known for its solid mineral deposits. The state has a blend of cultural and ethnic groups, including the Eggon, Tiv, and Gwandara. Lafia, the capital, is a growing urban center with a mix of traditional and modern lifestyles. Nasarawa is also home to Farin Ruwa Waterfalls, one of Nigeria’s most beautiful natural attractions.",
        population: "Nasarawa has a population of around 2.5 million people, with agriculture and mining as dominant industries.",
        safetydetails: "The state is generally peaceful, but some rural areas may have security concerns. Travelers should stay informed about local advisories.",
        funfact1: "⭐ Nasarawa is known as the 'Home of Solid Minerals.'",
        funfact2: "⭐ Farin Ruwa Waterfalls is one of the tallest waterfalls in Nigeria.",
        funfact3: "⭐ The state is a major producer of sesame seeds and yams.",
        culturetitle: "Nasarawa's culture is influenced by its diverse ethnic communities.",
        culture1: "Emir of Lafia’s Palace – A historic and cultural landmark.",
        culture2: "Traditional Wrestling – A popular sporting event in rural areas.",
        culture3: "Gwandara Festival – A celebration of the Gwandara people's heritage."
      },
      {
        name: "Niger",
        description: "Niger State, the largest state in Nigeria by landmass, is located in the North-Central region. It is home to the famous Gurara Waterfalls and the Kainji Dam, Nigeria’s major hydroelectric power source. Minna, the state capital, is a center for agriculture and trade. The state is predominantly occupied by the Nupe, Gwari, and Hausa ethnic groups, with a strong history of traditional leadership.",
        population: "Niger State has a population of approximately 5.5 million people, with Minna being the most urbanized city.",
        safetydetails: "Niger is relatively safe, but travelers should be cautious in remote areas due to sporadic security issues.",
        funfact1: "⭐ Niger is home to Nigeria’s largest hydroelectric power dam, Kainji Dam.",
        funfact2: "⭐ The Zuma Rock, a massive monolith, is located in Niger State.",
        funfact3: "⭐ Minna was once home to famous Nigerian leaders such as Ibrahim Babangida and Abdulsalami Abubakar.",
        culturetitle: "Niger’s culture is rich with Nupe and Gwari traditions.",
        culture1: "Nupe Day Festival – A celebration of the Nupe people’s history.",
        culture2: "Gurara Waterfalls – A site of cultural and religious significance.",
        culture3: "Traditional Pottery – The state is famous for its unique pottery designs."
      },
      {
        name: "Osun",
        description: "Osun State, created in 1991, is in southwestern Nigeria and is famous for its rich Yoruba heritage. Osogbo, the state capital, is home to the UNESCO-listed Osun-Osogbo Sacred Grove, a major cultural and spiritual site. The state is also known for its vibrant festivals, including the Osun Festival, which attracts tourists worldwide. Agriculture and small-scale industries drive the state's economy.",
        population: "Osun State has a population of about 4.7 million people, with a predominantly Yoruba-speaking population.",
        safetydetails: "Osun is generally peaceful, with occasional political tensions. Visitors should stay aware of local developments.",
        funfact1: "⭐ The Osun-Osogbo Sacred Grove is a UNESCO World Heritage Site.",
        funfact2: "⭐ Osun State is named after the Osun River, which is believed to have spiritual significance.",
        funfact3: "⭐ The state is known for its traditional textile industry, including Adire fabric.",
        culturetitle: "Osun’s culture is deeply rooted in Yoruba traditions.",
        culture1: "Osun Festival – A grand annual festival dedicated to the river goddess.",
        culture2: "Egungun Festival – A traditional masquerade festival celebrating Yoruba ancestors.",
        culture3: "Adire Textile – A famous indigo-dyed fabric handcrafted in Osogbo."
      },
      {
        name: "Plateau",
        description: "Plateau State, located in central Nigeria, is known for its scenic landscapes, temperate climate, and rich cultural heritage. The capital, Jos, was a colonial administrative hub and remains a center of tourism and education. The state is home to many ethnic groups, including the Berom, Afizere, and Anaguta, each contributing to its cultural diversity.",
        population: "Plateau State has an estimated population of about 4.2 million people.",
        safetydetails: "While Jos has seen periods of interethnic tension, the city remains relatively peaceful with security measures in place. Visitors should remain cautious in certain areas.",
        funfact1: "⭐ Plateau is known as the ‘Home of Peace and Tourism.’",
        funfact2: "⭐ Jos has one of the coolest climates in Nigeria due to its high altitude.",
        funfact3: "⭐ The state is a leading producer of potatoes and vegetables in Nigeria.",
        culturetitle: "Plateau’s culture is a blend of indigenous traditions and colonial influences.",
        culture1: "Nzem Berom Festival – Celebrates Berom heritage and traditions.",
        culture2: "Jos Museum – A historical site showcasing Nigeria’s cultural artifacts.",
        culture3: "Traditional Weaving – The state is known for its handcrafted fabrics."
      },
      {
        name: "Sokoto",
        description: "Sokoto State, located in northwestern Nigeria, is the historical seat of the Sokoto Caliphate, an important Islamic empire in West Africa. The capital, Sokoto, is a center for Islamic learning and culture. The state is largely populated by the Hausa and Fulani ethnic groups and is known for its rich history and agricultural activities.",
        population: "Sokoto State has a population of approximately 5.3 million people.",
        safetydetails: "The state is generally peaceful but travelers should stay informed about local security updates, especially in rural areas.",
        funfact1: "⭐ Sokoto is known as the ‘Seat of the Caliphate.’",
        funfact2: "⭐ The state experiences some of the hottest temperatures in Nigeria.",
        funfact3: "⭐ Sokoto is famous for its high-quality leather products.",
        culturetitle: "Sokoto’s culture is deeply rooted in Islamic and Fulani traditions.",
        culture1: "Durbar Festival – A grand equestrian display marking Islamic celebrations.",
        culture2: "Sokoto Caliphate Palace – A historic and cultural landmark.",
        culture3: "Tie and Dye Textiles – A traditional craft passed down through generations."
      },
      {
        name: "Taraba",
        description: "Taraba State, located in northeastern Nigeria, is known for its diverse ethnic groups, beautiful landscapes, and natural attractions. The capital, Jalingo, is a growing city with a mix of traditional and modern influences. Taraba is home to the Mambilla Plateau, which boasts Nigeria’s highest altitude and cool weather.",
        population: "Taraba has an estimated population of about 3 million people.",
        safetydetails: "The state is largely peaceful, but some remote areas may have security concerns. Travelers should stay informed about local advisories.",
        funfact1: "⭐ Taraba is known as ‘Nature’s Gift to the Nation.’",
        funfact2: "⭐ The Mambilla Plateau has the highest altitude in Nigeria.",
        funfact3: "⭐ Taraba is a major producer of tea and coffee in Nigeria.",
        culturetitle: "Taraba’s culture is influenced by its over 30 ethnic groups.",
        culture1: "Kambari Festival – Celebrates the culture of the Kambari people.",
        culture2: "Mambilla Plateau – A site of cultural and historical significance.",
        culture3: "Traditional Horse Riding – A popular activity among the Fulani people."
      },
      {
        name: "Yobe",
        description: "Yobe State, located in northeastern Nigeria, is known for its rich history, desert landscape, and agricultural activities. The capital, Damaturu, is a developing city that serves as an administrative and commercial hub. The state is predominantly populated by the Kanuri and Fulani ethnic groups, and it shares a border with Niger Republic.",
        population: "Yobe has an estimated population of about 3.4 million people.",
        safetydetails: "Yobe has experienced security challenges in the past but has seen improvements in stability. Travelers should stay informed and follow local security advisories.",
        funfact1: "⭐ Yobe is home to Nigeria’s portion of the Sahara Desert.",
        funfact2: "⭐ The state has some of the largest livestock markets in Nigeria.",
        funfact3: "⭐ Yobe is known for its date palm plantations and fish farming industry.",
        culturetitle: "Yobe’s culture is deeply rooted in Kanuri and Fulani traditions.",
        culture1: "Durbar Festival – A colorful equestrian parade during major celebrations.",
        culture2: "Pottery and Leatherwork – Handcrafted items made using traditional techniques.",
        culture3: "Traditional Wrestling – A popular sporting and cultural activity."
      },
      {
        name: "Zamfara",
        description: "Zamfara State, located in northwestern Nigeria, is known for its vast agricultural land and rich cultural heritage. The capital, Gusau, is a commercial and administrative center. The state is largely populated by the Hausa and Fulani ethnic groups, with Islam being the predominant religion.",
        population: "Zamfara has an estimated population of about 4.5 million people.",
        safetydetails: "The state has faced security concerns in rural areas. Travelers should be cautious and stay updated on local security reports.",
        funfact1: "⭐ Zamfara is one of Nigeria’s leading producers of gold and other minerals.",
        funfact2: "⭐ The state has a strong tradition of Islamic scholarship and learning.",
        funfact3: "⭐ Zamfara’s economy is largely driven by agriculture and cattle rearing.",
        culturetitle: "Zamfara’s culture is influenced by Hausa traditions and Islamic heritage.",
        culture1: "Hawan Sallah – A grand horse-riding festival during Islamic celebrations.",
        culture2: "Zamfara Leatherworks – The state is famous for high-quality leather products.",
        culture3: "Gidan Sarki Palace – A historic landmark representing Hausa architecture."
      }
  ]);

  return (
    <NigeriaContext.Provider value={{ states }}>
      {children}
    </NigeriaContext.Provider>
  );
};
